name: testenv
channels:
  - conda-forge
  - defaults
  - https://serverussnape.de/conda-channels/antares
dependencies:
  - blas=1.0
  - brotlipy=0.7.0
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=4.0.0
  - cryptography=3.3.1
  - icu=68.1
  - idna=2.10
  - intel-openmp=2019.4
  - jpeg=9d
  - krb5=1.17.1
  - libclang=11.0.0
  - libcxx=11.0.0
  - libedit=3.1.20191231
  - libffi=3.3
  - libiconv=1.16
  - libllvm11=11.0.0
  - libpng=1.6.37
  - libpq=12.3
  - libxml2=2.9.10
  - libxslt=1.1.33
  - lz4-c=1.9.3
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.2.1
  - mkl_random=1.1.1
  - mysql-common=8.0.22
  - mysql-libs=8.0.22
  - ncurses=6.2
  - nspr=4.29
  - nss=3.47
  - numpy-base=1.19.2
  - openssl=1.1.1j
  - pip=21.0.1
  - pycosat=0.6.3
  - pycparser=2.20
  - pyopenssl=20.0.1
  - pyqtgraph=0.11.0
  - pyside2=5.13.2
  - pysocks=1.7.1
  - python=3.7.9
  - python_abi=3.7
  - qt=5.12.9
  - readline=8.1
  - requests=2.25.1
  - ruamel_yaml=0.15.87
  - setuptools=52.0.0
  - six=1.15.0
  - sqlite=3.34.0
  - tk=8.6.10
  - tqdm=4.56.0
  - urllib3=1.26.3
  - wheel=0.36.2
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - beautifulsoup4==4.8.1
    - configparser==4.0.2
    - html5lib==1.0.1
    - lxml==4.4.2
    - neutronbraggedge==2.0.3
    - numpy==1.17.4
    - pandas==0.25.3
    - plotly==4.6.0
    - python-dateutil==2.8.1
    - pytz==2019.3
    - retrying==1.3.3
    - soupsieve==1.9.5
    - webencodings==0.5.1
