name: testenv
channels:
  - conda-forge
  - defaults
  - https://serverussnape.de/conda-channels/antares
dependencies:
  - blas
  - brotlipy
  - ca-certificates
  - certifi
  - cffi
  - chardet
  - cryptography
  - icu
  - idna
  - intel-openmp
  - jpeg
  - krb5
  - libclang
  - libcxx
  - libedit
  - libffi
  - libiconv
  - libllvm11
  - libpng
  - libpq
  - libxml2
  - libxslt
  - lz4-c
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - mysql-common
  - mysql-libs
  - ncurses
  - nspr
  - nss
  - numpy-base
  - openssl
  - pip
  - pycosat
  - pycparser
  - pyopenssl
  - pyqtgraph
  - pyside2
  - pysocks
  - python
  - python_abi
  - qt
  - readline
  - requests
  - ruamel_yaml
  - setuptools
  - six
  - sqlite
  - tk
  - tqdm
  - urllib3
  - wheel
  - xz
  - yaml
  - zlib
  - zstd
  - pip:
    - beautifulsoup4
    - configparser
    - html5lib
    - lxml
    - neutronbraggedge
    - numpy
    - pandas
    - plotly
    - python-dateutil
    - pytz
    - retrying
    - soupsieve
    - webencodings
